keyboard.bindings = [
    { key = "Up", mods = "Control | Shift", action = "Up" }
]

colors.draw_bold_text_with_bright_colors = false

[window]
title = "Alacritty"
padding = { x = 4, y = 4 }
# decorations = "None"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
size = 11
offset = { x = 0, y = 3 }
glyph_offset = { x = 0, y = 1 }

[colors.primary]
foreground = "#d2d2d2"
background = "#252323"

[colors.normal]
black = "#111213"
red = "#e69f9f"
green = "#8ea77b"
yellow = "#d4bf7e"
blue = "#8ba3b3"
magenta = "#aa92ad"
cyan = "#85b3b3"
white = "#d7d5cf"

[cursor.style]
shape = "block"
blinking = "off"

