# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[window]
title = "Alacritty"
padding = { x = 12, y = 12 }
dynamic_padding = true
decorations = "Full"
opacity = 1.0

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
size = 11
offset = { x = 0, y = 6 }
glyph_offset = { x = 0, y = 2 }

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
foreground = "#d2d2d2"
background = "#252323"

[colors.normal]
black = "#111213"
red = "#bb443a"
green = "#8ea77b"
yellow = "#d4bf7e"
blue = "#8ba3b3"
magenta = "#aa92ad"
cyan = "#85b3b3"
white = "#d7d5cf"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
# cursor = "#5fd7af"

[cursor]
style = { shape = "block", blinking = "never" }
# blink_interval = 750

[keyboard]
bindings = [
    { key = "Up", mods = "Control | Shift", action = "ScrollLineUp" },
    { key = "Down", mods = "Control | Shift", action = "ScrollLineDown" },
    { key = "F", mods = "Control | Shift", action = "ToggleFullScreen" },
    { key = "A", mods = "Control | Shift", action = "ToggleViMode" }
]

