#!/usr/bin/env bash

shopt -s dotglob nullglob

dotfiles="$HOME/dotfiles/home"

# (re)create symbolic links
for f in "$dotfiles"/*; do
    if [ -d "$f" ]; then
        dest="$HOME/${f##*/}"
        mkdir -p "$dest"
        ln -sriv "$f"/* "$dest"
    else
        ln -siv "$f" "$HOME"
    fi
done

