# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[window]
title = "Alacritty"
# padding = { x = 12, y = 8 }
# dynamic_padding = true
decorations = "Full"
opacity = 0.96

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
size = 11
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 0 }


[colors]
draw_bold_text_with_bright_colors = false

# Kanagawa Alacritty Colors
selection = { text = "0xc8c093", background = "0x2d4f67" }

[colors.primary]
foreground = "#d2d2d2"
background = "#201f1f"
# background = "0x1f1f28"
# foreground = "0xdcd7ba"

[colors.normal]
black = "0x090618"
red = "0xc34043"
green = "0x76946a"
yellow = "0xc0a36e"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x6a9589"
white = "0xc8c093"

[colors.bright]
black = "0x727169"
red = "0xe82424"
green = "0x98bb6c"
yellow = "0xe6c384"
blue = "0x7fb4ca"
magenta = "0x938aa9"
cyan = "0x7aa89f"
white = "0xdcd7ba"

# [colors.primary]
# foreground = "#d2d2d2"
# background = "#201f1f"

# [colors.normal]
# black = "#111213"
# red = "#bb443a"
# green = "#8ea77b"
# yellow = "#d4bf7e"
# blue = "#8ba3b3"
# magenta = "#aa92ad"
# cyan = "#85b3b3"
# white = "#d2d2d2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
# cursor = "#d4bf7e"

[cursor]
style = { shape = "block", blinking = "never" }
# blink_interval = 750

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "Up", mods = "Control | Shift", action = "ScrollLineUp" },
    { key = "Down", mods = "Control | Shift", action = "ScrollLineDown" },
    { key = "F", mods = "Control | Shift", action = "ToggleFullScreen" },
    { key = "A", mods = "Control | Shift", action = "ToggleViMode" },
    # { key = "Return", mods = "Shift",   chars = "\x1b[13;2u" },
    # { key = "Return", mods = "Control", chars = "\x1b[13;5u" },
]

[selection]
save_to_clipboard = true

