# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[window]
title = "Alacritty"
# padding = { x = 12, y = 8 }
# dynamic_padding = true
decorations = "Full"
opacity = 1.0

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
size = 11
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 0 }

[colors]
draw_bold_text_with_bright_colors = false
indexed_colors = [
    { index = 16, color = "#fec43f" },
    { index = 17, color = "#ff9580" }
]

[colors.primary]
foreground = "#d2d2d2"
background = "#201f1f"

[colors.normal]
black = "#111213"
red = "#ff5f59"
green = "#44bc44"
yellow = "#d0bc00"
blue = "#2fafff"
magenta = "#feacd0"
cyan = "#00d3d0"
white = "#d7d5cf"

[colors.cursor]
text = "CellBackground"
# cursor = "CellForeground"
cursor = "#d0bc00"

[cursor]
style = { shape = "block", blinking = "never" }
# blink_interval = 750

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "Up", mods = "Control | Shift", action = "ScrollLineUp" },
    { key = "Down", mods = "Control | Shift", action = "ScrollLineDown" },
    { key = "F", mods = "Control | Shift", action = "ToggleFullScreen" },
    { key = "A", mods = "Control | Shift", action = "ToggleViMode" },
    # { key = "Return", mods = "Shift",   chars = "\x1b[13;2u" },
    # { key = "Return", mods = "Control", chars = "\x1b[13;5u" },
]

[selection]
save_to_clipboard = true

